services:
  - type: web
    name: todo-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    # Health check configuration
    healthCheckPath: /health
    # Auto-scaling configuration
    plan: free
    # Build and runtime settings
    buildFilter:
      paths:
        - "**/*"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: todo_app_jwt_secret_key_2024_secure_and_unique_please_change_in_production
      - key: MONGODB_URI
        value: mongodb+srv://adil:Adil%402005@cluster1.vh0gvd7.mongodb.net/todoapp?retryWrites=true&w=majority

