services:
  - type: web
    name: todo-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        value: wJ3+uO/ZFt4j1x2bL7bQmMbnA1LZk8K+7q8Vt9vHgxw=

